### ISSUE TITLE
Doesn't work in ie10

### ISSUE THREAD

**Issue by ekeric13** [borisirota/webworkify-webpack#24]
When creating a web worker in ie10, the page fails to load and in the console ie10 throws a “SCRIPT5002 function expected”

**Comment by borisirota** [comment]
I don't have ie10
 can you try and isolate the problem ? I think there is need to check from [line 66](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L66)

The problem seems like invocation of something that isn't a function => isn't supported in ie10.
 
Maybe `window.Blob` isn't a function ?
Maybe `URL.createObjectURL` isn't a function ?
Maybe `window.Worker` isn't a function ?

Thanks

**Comment by ekeric13** [comment]
It's hard to debug since IE 10's errors are terrible and I only access [ie10](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) through a [virtual machine](https://www.virtualbox.org/wiki/Downloads).

Eventually I gave up trying to support ie10.
My best lead was this stackoverflow thread: http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

Which seemed to imply you needed to use eval. Though I cannot discern what you are suppose to eval, the web worker file script, or the code on [line 66](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L66) that you referred to.

I saw this problem with all inline web workers, not just this library.
