### ISSUE TITLE
Jest test

### ISSUE THREAD

**Issue by BorisTB** [borisirota/webworkify-webpack#30]
Hi, I absolutely love this package, but is there any way to test my code in jest when I use webworkify-webpack?

I'm getting this error 

`ReferenceError: __webpack_modules__ is not defined`

**Comment by borisirota** [comment]
Hi @BorisTB 

I'm not testing code that uses this module and I'm not using jest so can't be very informative about this use case.

In general, there isn't much meaning to this module outside of webpack's scope and in order to achieve its goal there is need to use webpack internals at runtime (which are globals like `__webpack_modules__`), so unless you bundle the code you want to test with webpack, webpack internals won't be defined.

That being said, its does possible to test code that uses `webworkify-webpack` with various techniques (dependency injection, mocks, etc.) but it really depends on the code architecture.

In any case, I'm open to suggestions in order to make testing code which uses this module easier :)

**Comment by ywen** [comment]
@BorisTB have you found a solution yet?
